env:
    MANIFEST: https://github.com/RisingTechOSS/android -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    DT_LINK: https://github.com/Shravan55555/device_realme_RMX1901_13.git -b Rise
    DT_PATH: device/realme/RMX1901
    VT_LINK: https://github.com/shravansayz/vendor_realme_RMX1901.git  -b 13
    KT_LINK: https://github.com/H1mJT/kernel_realme_RMX1901.git -b x.337_ksu
    VT_PATH: vendor/realme/RMX1901
    KT_PATH: kernel/realme/RMX1901
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: r*.zip
    CLO: RMX1901:AppDrive
    CLO_1: ENCRYPTED[!898649562db3ebfe7fc561b335e268170e5375730036b54e68517dd7d2e30102bc622e6a87f0dd4e878d9f045afb74da!]
    URI: example
    ROM_U: 0
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Storage-Checker_script:
      - ./d0wnl0ad

  Sync_script:
      - ./syn0

  Build_script:
      - ./bu1ld

  upload_script:
      - sh upl0ad
